### ISSUE TITLE
Deneme

### ISSUE THREAD

**Issue by alprcrk** [happyknighttk/TobetoPlatformFinalProject_Pair_4#37]
lorem ipsum

**Comment by enessamancioglu** [comment]
Enes was here

**Comment by enessamancioglu** [comment]
![CleanArchitecture](https://github.com/happyknighttk/TobetoPlatformFinalProject_Pair_4/assets/82954238/27d16929-472e-4891-aca8-e5cf70d44403)

**Comment by enessamancioglu** [comment]
closed
